In [1]:
import numpy as np

In [2]:
a = np.zeros(3)

In [3]:
a

array([0., 0., 0.])

In [4]:
type(a)
type(a[0])

numpy.float64

In [5]:
b= np.zeros(20)

In [6]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
b.shape

(20,)

In [8]:
b.shape = (20,1)
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
z=np.ones(10)

In [10]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
z=np.empty(3)

In [12]:
z

array([0., 0., 0.])

In [13]:
z=np.linspace(2,10,5)

In [14]:
z

array([ 2.,  4.,  6.,  8., 10.])

In [15]:
b=np.array([10,20])

In [16]:
b

array([10, 20])

In [17]:
x = [1,2,3,4,5,6,7,8,9,]
y = np.array([x])

In [18]:
y

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
type(y)

numpy.ndarray

In [20]:
n = [[1,2,3,4,5],[6,7,8,9,10]]

In [21]:
m = np.array([n])
m

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [22]:
#m.shape
?m

In [23]:
?m.shape

In [24]:
z1 = np.random.seed(0)
z1 = np.random.randint(10 , size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [25]:
z1[0]

5

In [26]:
z1[-1]

9

In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> hi
No Python documentation found for 'hi'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> pandas
Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    
    **pandas** is a Python package providing fast, fle